In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


In [1]:
class MeraLR :

    def __init__(self):
        self.m = None
        self.b = None

    def fit(self,x_train,y_trian):

        num = 0
        den = 0

        for i in range(x_train.shape[0]):
            
            num += ((x_train[i]-x_train.mean())*(y_train[i]-y_train.mean()))
            den += ((x_train[i]-x_train.mean())*(x_train[i]-x_train.mean()))

        self.m = num/den
        self.b = y_train.mean() - (self.m * x_train.mean())
        print(self.m)
        print(self.b)

    def predict(self,x_test):
        
        return self.m * x_test + self.b



In [3]:
df = pd.read_csv('placement.csv')
df.head()

cgpa  package
0  6.89     3.26
1  5.12     1.98
2  7.82     3.25
3  7.42     3.67
4  6.94     3.57

In [26]:
x = df.iloc[:,0].values.reshape(-1,1)
y = df.iloc[:,1].values

x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=.8, random_state=2)

In [27]:
y_train

array([3.13, 3.91, 2.25, 2.3 , 4.06, 3.18, 2.7 , 2.49, 3.15, 2.99, 4.08,
       4.14, 2.6 , 2.44, 2.71, 2.72, 1.63, 2.31, 2.51, 3.5 , 2.24, 2.58,
       2.42, 2.54, 4.37, 2.17, 3.14, 2.19, 3.54, 1.54, 2.72, 3.98, 2.46,
       3.  , 1.98, 2.65, 3.75, 3.67, 2.93, 3.08, 2.21, 2.84, 3.76, 3.03,
       2.09, 3.26, 2.16, 2.7 , 3.83, 2.88, 3.16, 3.04, 3.13, 3.04, 4.6 ,
       3.26, 2.85, 2.09, 3.31, 3.89, 1.87, 3.11, 2.4 , 3.48, 3.08, 2.76,
       2.93, 3.39, 2.35, 3.08, 2.14, 3.24, 1.73, 3.24, 3.44, 2.69, 3.33,
       2.42, 2.57, 3.55, 2.66, 1.53, 2.98, 2.84, 3.52, 3.16, 3.82, 2.6 ,
       1.61, 2.2 , 2.99, 3.12, 2.74, 2.83, 2.77, 2.35, 2.19, 3.42, 4.02,
       3.89, 3.15, 3.99, 3.42, 3.08, 2.46, 2.61, 3.49, 3.76, 2.82, 4.03,
       2.99, 2.73, 2.18, 3.09, 3.96, 2.1 , 3.33, 4.62, 3.47, 2.48, 4.43,
       4.11, 3.44, 3.18, 3.02, 4.06, 2.26, 1.48, 2.94, 2.89, 2.72, 3.09,
       2.73, 4.36, 3.  , 3.79, 2.59, 2.87, 3.57, 1.37, 3.6 , 2.43, 3.33,
       2.31, 3.4 , 3.89, 4.25, 3.26, 3.67, 2.79, 3.

In [28]:
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [41]:
lr.predict(x_test[0].reshape(-1,1))

array([3.89111601])

In [42]:
# Using our own class

my = MeraLR()
my.fit(x_train,y_train)

[0.55795197]
[-0.89611192]


In [43]:
lr.coef_,lr.intercept_

(array([0.55795197]), -0.8961119222429144)

In [44]:
my.predict(x_test[0])

array([3.89111601])

In [46]:
from sklearn.datasets import load_diabetes

df = load_diabetes()

In [48]:
x = df.data
y = df.target

In [53]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=.8, random_state=2)

In [54]:
x_train.shape

(353, 10)

In [55]:
lr.fit(x_train,y_train)

LinearRegression()

In [56]:
lr.coef_, lr.intercept_

(array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
        -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
         861.12700152,   52.42112238]),
 151.88331005254167)

In [57]:
lr.score(x_test,y_test)

0.4399338661568968

In [58]:
### Creating our own class

class MeraLR1:
    def __init__(self):
        self.coef_= None
        self.intercept_ = None

    def fit(self,x_train,y_train):
        x_train = np.insert(x_train,0,1, axis=1) # Inserting 1 column at 0th index

        ## calculating the coeff
        betas = np.linalg.inv(np.dot(x_train.T,x_train)).dot(x_train.T).dot(y_train) # Beta = ((X^T.X)^-1).(X^T).(Y)
        self.coef_ = betas[1:]
        self.intercept_ = betas[0]

    def predict(self,x_test):
        y_pred = np.dot(x_test,self.coef_) + self.intercept_
        return y_pred

In [59]:
lr1 = MeraLR1()
lr1.fit(x_train,y_train)

In [61]:
lr1.intercept_ ,lr1.coef_

(151.88331005254165,
 array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
        -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
         861.12700152,   52.42112238]))

In [62]:
y_pred = lr1.predict(x_test)

In [63]:
from sklearn.metrics import r2_score

r2_score(y_test,y_pred)

0.4399338661568961

In [64]:
## Results are same as sklearn.model_selection.LinearRegression()